MVCpgs/Controllers/HomeController.cs
using MVCpgs.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using MVCpgs.Services;

namespace MVCpgs.Controllers
{
    public class HomeController : Controller
    {
        GmailEmailService _emailService;

        public HomeController()
        {
            _emailService = new GmailEmailService();
        }

        public ActionResult Index()
        {
            var tmp = 8;
            var tmp2 = 6;
            var tmp3 = 4;
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        [HttpGet]
        public ViewResult Contact()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Contact(UserContact userContact)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            
            await _emailService.Send(userContact);

            return View("thanks", userContact);
        }
    }
}

MVCpgs/Controllers/NoteDBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCpgs.Models;

namespace MVCpgs.Controllers
{
    public class NoteDBController : Controller
    {
        // GET: NoteDB
        public ActionResult Index()
        {
            var entities = new NotesDBEntities();

            return View(entities.NoteViewModels.ToList());
        }
    }
}

MVCpgs/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCpgs/Views/Home/Contact.cshtml
@model MVCpgs.Models.UserContact
@{
    ViewBag.Title = "Contact";
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>
}
   

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>
<body>
    @using (Html.BeginForm("Contact", "home", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <h4>Send your comments.</h4>
        <hr />

        @Html.ValidationSummary()
        //<p>Imie i Nazwisko: @Html.TextBoxFor(x => x.Name) </p>
        <p>@Html.LabelFor(x => x.Name) @Html.TextBoxFor(x => x.Name) </p>

        <p>@Html.LabelFor(x => x.Email) @Html.TextBoxFor(x => x.Email)</p>
        <p>
   @Html.LabelFor(x => x.LikeBeer)
     @Html.DropDownListFor(x => x.LikeBeer, new[]
{
    new SelectListItem() {Text = "Tak, lubie!.", Value = bool.TrueString },
    new SelectListItem() {Text = "Nie, nie lubie :(", Value = bool.FalseString }
}, "wybierz opcje")
        </p>
        <p>@Html.LabelFor(x => x.MsgToUs) @Html.TextAreaFor(x => x.MsgToUs, new { @rows = 7, @cols = 35 }) </p>
        <input type="submit" value="Wyślij zapytanie" />
    }
</body>
<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

MVCpgs/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@Html.Action("Index", "NoteDB")

MVCpgs/Views/Home/Thanks.cshtml
@model MVCpgs.Models.UserContact

@{
    ViewBag.Title = "" ;
    <h2>@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>
}
   
<div>
    @if (Model.LikeBeer == true)
    {
     <h1>Dziekujemy za kontakt ,@Model.Name</h1>
     @:postaramy sie oppowiedziec na twoje pytanie.
    }
    else
    {
     <h1>Nie okłamuj nas!  @Model.Name</h1>
     @: Wiemy że lubisz ale żona ci zabrania.
    }

</div>